# Generated by Django 4.2.15 on 2024-08-31 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('job', models.CharField(blank=True, max_length=15, null=True)),
                ('person',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='personal_info',
                                      to='quickstart.person')),
            ],
        ),
    ]
