### GET All Persons
GET http://127.0.0.1:8000/api/person

### GET Person by ID
GET http://127.0.0.1:8000/api/person/7

### GET Person by Name
GET http://127.0.0.1:8000/api/person?first_name=Yusha

### POST Create New Person
POST http://127.0.0.1:8000/api/person/
Content-Type: application/json

{
  "first_name": "Abdullah",
  "last_name": "Muhammad"
}

### PUT Update Person by ID
PUT http://127.0.0.1:8000/api/person/7/
Content-Type: application/json

{
  "first_name": "NAHID X",
  "last_name": "Hassan"
}

### PUT Update Person by ID
PATCH http://127.0.0.1:8000/api/person/7/
Content-Type: application/json

{
  "first_name": "NAHID"
}

### DELETE Person by ID
DELETE http://127.0.0.1:8000/api/person/18